# Generated by Django 4.1.2 on 2022-10-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('work', models.CharField(max_length=20)),
                ('quote', models.CharField(max_length=40)),
                ('twitter_handle', models.CharField(max_length=120)),
                ('twitter_link', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='/')),
            ],
        ),
    ]
